[package]
name = "ngxav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["derive"] }
rayon = "1.8.1"
regex = "1.10.3"
threadpool = "1.8.1"
tokio = { version = "1.36.0", features = ["full"] }
