name: Run Tests
run-name: Build & Test Project Across 16+ Test Cases 🚀
on: [push]
jobs:
  ExecuteTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - run: cargo build -r
      - run: cd tests
      - run: cargo run
