name: Run Tests
run-name: Build & Test Project Across 16+ Test Cases 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    -name: Enable Debug
      run: export RUST_BACKTRACE=1

    - name: Build project
      run: cargo build -r --verbose

    - name: Run Tests
      run: cd tests && cargo run
